-- =============================================================
-- AI Operations Copilot — Phase 7: governance seed
-- Experiment records are REAL results generated by
-- scripts/run-lab-experiments.mjs against the live Gemini API
-- (raw evidence: docs/governance-data/experiments.json).
-- Run AFTER 004_governance.sql. Idempotent.
-- =============================================================

do $seed$
begin

if not exists (select 1 from public.tool_experiments where tool_name = 'gemini-3.5-flash') then

  -- ---------- Experiment A1: gemini-3.5-flash on the F-004 lead-analysis prompt ----------
  insert into public.tool_experiments (id, tool_name, tool_category, business_task, test_definition, output_summary, quality_notes, speed_notes, cost_notes, ease_notes, integration_notes, limitations)
  values (
    '33333333-3333-3333-3333-333333333301',
    'gemini-3.5-flash', 'llm',
    'Admissions (F-004): qualify an incoming lead into score/category/intent/summary/recommended_action JSON',
    '5 runs of the exact production lead-analysis prompt (JSON mode, temperature 0.4) over 3 rotating real leads: an urgent HOT IELTS lead, a vague COLD inquiry, and a mid-funnel WARM Business English lead. Graded on JSON parseability, schema validity, and HOT/WARM/COLD correctness.',
    '5/5 parseable JSON, 5/5 schema-valid, 4/5 category calls correct. All failures of note: one WARM lead was scored into an adjacent band. Summaries were consistently well-written and actionable.',
    'High: strict JSON contract always honored; summaries specific and counselor-ready. One band error on the least clear lead.',
    'avg 3,693 ms per call (5 runs; range roughly 2.5-5.5 s). Noticeably slower than flash-lite for the same prompt.',
    'Free tier. Same per-model daily quota bucket as flash-lite; ~2-3x the output tokens of flash-lite due to longer reasoning.',
    'Identical API surface to flash-lite; swapping models is a one-line change (validated in this project).',
    'Native JSON mode (responseMimeType) worked on every call; integrates directly with the n8n HTTP node and the schema-gate pattern.',
    'Occasional over-qualification of marginal leads (one band error). Free-tier daily quota can exhaust mid-testing (observed 2026-09-05).'
  );

  -- ---------- Experiment A2: gemini-3.5-flash-lite, same test ----------
  insert into public.tool_experiments (id, tool_name, tool_category, business_task, test_definition, output_summary, quality_notes, speed_notes, cost_notes, ease_notes, integration_notes, limitations)
  values (
    '33333333-3333-3333-3333-333333333302',
    'gemini-3.5-flash-lite', 'llm',
    'Admissions (F-004): qualify an incoming lead into score/category/intent/summary/recommended_action JSON',
    'Identical protocol to the gemini-3.5-flash experiment: 5 runs, same 3 rotating leads, same grading.',
    '5/5 parseable JSON, 5/5 schema-valid, 5/5 category calls correct — outperformed the larger flash model on this run.',
    'High: matched flash on all hard requirements and was the only model to classify all 3 leads correctly on this run. Summaries slightly shorter but still actionable.',
    'avg 1,056 ms per call — roughly 3.5x faster than flash on the same prompt.',
    'Free tier; cheaper per token than flash on paid tier.',
    'Same API surface; chosen as this project''s production model (AI_MODEL env).',
    'Same native JSON mode integration; currently powers the live n8n pipeline and all 5 department AI tools.',
    'Summaries less elaborate than flash; for this use case that is neutral-to-positive.'
  );

  -- ---------- Experiment B: retired model (negative result) ----------
  insert into public.tool_experiments (id, tool_name, tool_category, business_task, test_definition, output_summary, quality_notes, speed_notes, cost_notes, ease_notes, integration_notes, limitations)
  values (
    '33333333-3333-3333-3333-333333333303',
    'gemini-2.0-flash (retired)', 'llm',
    'Negative control: confirm behavior of a Google-retired model on the same integration path',
    'Single call with "Reply with exactly: ok" to the retired model through the identical HTTP integration used by production.',
    'HTTP 404: "This model models/gemini-2.0-flash is no longer available. Please update your code to use models/gemini-3.6-flash." Latency 159 ms.',
    'n/a — a deliberate negative result, kept as evidence.',
    'Fails fast (<200 ms), which is good: dead-model detection is cheap.',
    'n/a.',
    'Failure mode is clear and actionable (Google even names the successor model).',
    'This exact 404 previously produced a misleading "AI service is unreachable" user message until the app learned to classify 404 as a permanent config error (AI_CONFIG) — see docs/dev-fix-log.md #1/#2.',
    'Retired models return 404, not an error marked "deprecation" — version pinning and config-error classification are mandatory.'
  );

  -- ---------- Experiment C: JSON mode vs plain-prompt extraction ----------
  insert into public.tool_experiments (id, tool_name, tool_category, business_task, test_definition, output_summary, quality_notes, speed_notes, cost_notes, ease_notes, integration_notes, limitations)
  values (
    '33333333-3333-3333-3333-333333333304',
    'gemini-3.5-flash-lite (JSON mode vs plain prompt)', 'llm',
    'Academic (F-023): generate a 3-question IELTS vocabulary quiz as strict JSON',
    '3 runs per method on the quiz task: (a) native JSON mode (responseMimeType=application/json) vs (b) plain prompt asking for JSON. Graded on parse success with the production markdown-fence-stripping parser.',
    'Both methods: 3/3 parseable, all question arrays complete. avg latency 1,738 ms (JSON mode) vs 1,709 ms (plain).',
    'Parity on this task — the lite model respects "only JSON" instructions well even without the MIME type.',
    'No meaningful latency difference.',
    'Identical (both free tier).',
    'JSON mode removes the need for fence-stripping defensive parsing; plain prompt works but relies on instruction-following.',
    'Project convention (R-02) is JSON mode everywhere regardless, as a guardrail — the near-parity result means the guardrail is cheap.',
    'On harder/longer outputs the guardrail may matter more; this test used a short, well-structured task.'
  );

end if;

-- ---------- F-027: the adoption decision, scored from the experiments ----------
if not exists (select 1 from public.tool_evaluations where tool_name = 'gemini-3.5-flash-lite') then
  insert into public.tool_evaluations (tool_name, use_case, scores, total_score, recommendation, rationale, strengths, weaknesses, experiment_refs)
  values (
    'gemini-3.5-flash-lite',
    'Primary LLM for all AI features: lead qualification (F-004), email drafting (F-008), and the 5 interactive department tools (F-020..F-024)',
    '{"quality": 4, "accuracy": 5, "cost": 5, "speed": 5, "ease": 5, "integration": 5, "privacy": 4, "scalability": 3}',
    36,
    'recommended',
    'Recommended, conditional on free-tier quota limits. On the head-to-head lead-qualification experiment it matched the larger flash model on every hard requirement (5/5 parse, 5/5 schema) while classifying all leads correctly and running ~3.5x faster (avg 1,056 ms vs 3,693 ms). Cost and ease are best-in-class for this project: free tier, one-line model swap, native JSON mode. Scalability is the honest weak spot — the free tier''s per-model daily quota exhausted mid-testing once (documented in the experiment log), so production growth would need a paid tier or model fallback. Data privacy: synthetic data only in this prototype; any real deployment must review Google''s data-processing terms.',
    '{"Fastest model tested (1.0s avg on the production prompt)", "Perfect JSON schema compliance across all test runs", "Only model to classify all 3 test leads correctly", "Free tier with generous daily quota", "Zero-friction swap between models (one env var)", "Native JSON mode guardrail at no latency cost"}',
    '{"Per-model daily quota can exhaust on heavy days (observed once)", "Summaries less elaborate than gemini-3.5-flash", "Model retirement cadence is fast (2.0/2.5 generations already 404) — pin and monitor"}',
    array['33333333-3333-3333-3333-333333333301','33333333-3333-3333-3333-333333333302','33333333-3333-3333-3333-333333333303','33333333-3333-3333-3333-333333333304']::uuid[]
  );
end if;

end
$seed$;
