'use client'
import Link from 'next/link'
import type { ChatCard } from '@/lib/chat/cards'

const text=(v:unknown, fallback='—'):string=>typeof v==='string'&&v? v:fallback
export function RichCards({cards}:{cards:ChatCard[]}){ if(!cards.length)return null; return <div className="space-y-2">{cards.map((card,i)=>{
  if(card.type==='lead'){const l=card.lead; const leadId=typeof l.id==='string'?l.id:null; return <article key={i} className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Lead</p><p className="font-semibold text-slate-900">{text(l.name)}</p><p className="text-xs text-slate-500">{text(l.course_interest,'No course recorded')}</p></div><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-700">{text(l.category,'unclassified')}</span></div>{leadId&&<Link className="mt-2 inline-block text-xs font-medium text-blue-600 hover:underline" href={'/leads/'+leadId}>Open lead</Link>}</article>}
  if(card.type==='task')return <article key={i} className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Follow-up task</p><p className="font-medium text-slate-900">{text(card.task.title,'Task created')}</p><p className="mt-1 text-xs text-slate-500">{text(card.task.priority,'medium')} priority · due {text(card.task.due_at,'soon')}</p></article>
  if(card.type==='knowledge')return <article key={i} className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Sources consulted</p><ul className="mt-1 space-y-1">{card.results.map((r,j)=><li key={j} className="text-sm text-slate-700"><strong>{text(r.title)}</strong><span className="block text-xs text-slate-500">{text(r.excerpt,'')}</span></li>)}</ul></article>
  if(card.type==='email') return <article key={i} className="rounded-2xl border border-indigo-100 bg-indigo-50 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-indigo-600">Email draft · dry-run</p><p className="font-medium text-slate-900">{text(card.email.subject,'Untitled draft')}</p><p className="mt-1 line-clamp-3 whitespace-pre-wrap text-xs text-slate-600">{text(card.email.body,'No body preview')}</p></article>
  return <article key={i} className="rounded-2xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800">Approval required: review the proposed action in Agent Approvals.</article>
 })}</div> }
